// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiMd8pxzkKQmAdXl0TAazHd9_FGQR_Q8E',
    appId: '1:854161407983:web:fb4b82cbf909362ee4801a',
    messagingSenderId: '854161407983',
    projectId: 'zapcart-b41fa',
    authDomain: 'zapcart-b41fa.firebaseapp.com',
    storageBucket: 'zapcart-b41fa.firebasestorage.app',
    measurementId: 'G-S6BWYEB1L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFc4D9a0Vqj1RTOczaiGaQqRkEH8mDbGk',
    appId: '1:854161407983:android:0292dc76e0a26983e4801a',
    messagingSenderId: '854161407983',
    projectId: 'zapcart-b41fa',
    storageBucket: 'zapcart-b41fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVnd25VqlAY1nvAXqFJMrnFvc0kQI5lTk',
    appId: '1:854161407983:ios:70626bf039e0cbd6e4801a',
    messagingSenderId: '854161407983',
    projectId: 'zapcart-b41fa',
    storageBucket: 'zapcart-b41fa.firebasestorage.app',
    iosBundleId: 'com.example.zapcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVnd25VqlAY1nvAXqFJMrnFvc0kQI5lTk',
    appId: '1:854161407983:ios:70626bf039e0cbd6e4801a',
    messagingSenderId: '854161407983',
    projectId: 'zapcart-b41fa',
    storageBucket: 'zapcart-b41fa.firebasestorage.app',
    iosBundleId: 'com.example.zapcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiMd8pxzkKQmAdXl0TAazHd9_FGQR_Q8E',
    appId: '1:854161407983:web:709b7fad882ee5b7e4801a',
    messagingSenderId: '854161407983',
    projectId: 'zapcart-b41fa',
    authDomain: 'zapcart-b41fa.firebaseapp.com',
    storageBucket: 'zapcart-b41fa.firebasestorage.app',
    measurementId: 'G-YJCCY2802L',
  );
}
